services:
  db:
    image: postgres:18-alpine
    container_name: local-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - local_db_data:/var/lib/postgresql/data
volumes:
  local_db_data: