services:
  db:
    image: postgres:16-alpine
    container_name: prod-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    image: ghcr.io/sniperdev/budget-planner-api:latest
    container_name: prod-api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app?schema=public
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped

  web:
    image: ghcr.io/sniperdev/budget-planner-web:latest
    container_name: prod-web
    environment:
      NODE_ENV: production
      PORT: 3001
      NEXT_PUBLIC_API_URL: http://api:3000
    depends_on:
      - api
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  prod_db_data: